server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: administration
          uri: http://localhost:8085/
          predicates:
            - Path=/administration/**
        - id: postcom
          uri: http://localhost:8086/
          predicates:
            - Path=/post-com/**


       