server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: administration
          uri: http://localhost:8085/
          predicates:
            - Path=/administration/**
        - id: postcom
          uri: http://localhost:8086/
          predicates:
            - Path=/post-com/**
        - id: search
          uri: http://localhost:8087/
          predicates:
            - Path=/search/**
        - id: login
          uri: http://localhost:8088/
          predicates:
            - Path=/user/**
        - id: notification
          uri: http://localhost:8089/
          predicates:
            - Path=/notification/**


       